version: '3.8'
# definir container
services:

  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
  # spring app
  achat_backend:
    image: anouarmh15/achat:1.0.0
    restart: unless-stopped
    ports:
      - "8089:8089"
    depends_on:
      - db
    volumes:
      - backend:/backend
    environment:
      SPRING_DATASOURCE_URL : jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db_data:
  backend: